backend/controllers/TransactionController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Transaction;
use common\models\TransactionSearch;
use common\components\CommonController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use backend\models\TransactionAdminForm;
use yii\web\ForbiddenHttpException;
use common\models\ViolatorLog;
use common\models\User;

/**
 * TransactionController implements the CRUD actions for Transaction model.
 */
class TransactionController extends CommonController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }



    /**
     * Creates a new Transaction model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreateTransfer($id)
    {
        $model = new TransactionAdminForm(['scenario' => 'sendMoney']);
        $model->currentUserId = $id;

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->sendMoney();
            Yii::$app->session->setFlash('success', 'Операция успешно проведена.');
            return $this->redirect(['user/view', 'id' => $id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionEnterSum($id)
    {
        $model = new TransactionAdminForm();
        $model->currentUserId = $id;

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->depositMoney();
            Yii::$app->session->setFlash('success', 'Операция успешно проведена.');
            return $this->redirect(['user/view', 'id' => $id]);
        } else {
            return $this->render('enterSum', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Finds the Transaction model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Transaction the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Transaction::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\User;
use yii\data\ActiveDataProvider;
use common\components\CommonController;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;
use common\models\ViolatorLog;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use backend\models\UserAdminForm;

use common\models\Transaction;
use common\models\UserSearch;
use common\models\Account;
use yii\data\SqlDataProvider;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends CommonController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }



    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {

    /*    $count = Yii::$app->db->createCommand('
            SELECT COUNT(*) FROM '.User::tableName().' WHERE status = :status
        ', [':status' => User::STATUS_ACTIVE])->queryScalar();

        $params = [':status' => User::STATUS_ACTIVE, ':time_begin' => 0, ':sender_type' => Transaction::SENDER_TYPE_USER];


        $sql = 'SELECT u.id, u.created_at, u.username, a.balance, t_plus.p_amount AS sum_plus, t_minus.m_amount AS sum_minus
        FROM '.User::tableName().' AS u
        LEFT JOIN '.Account::tableName().' AS a ON (a.user_id = u.id)
        LEFT JOIN     (
                SELECT t_p.received_by, SUM(t_p.amount) AS p_amount
                FROM '.Transaction::tableName().' AS t_p
                WHERE
                    t_p.time >= :time_begin
                GROUP BY t_p.received_by
            ) AS t_plus ON (t_plus.received_by = u.id)

        LEFT JOIN   (
                SELECT t_m.sent_by, SUM(t_m.amount) AS m_amount
                FROM '.Transaction::tableName().' AS t_m
                WHERE
                    t_m.sender_type = :sender_type AND
                    t_m.time >= :time_begin
                GROUP BY t_m.sent_by
            ) AS t_minus ON (t_minus.sent_by = u.id)

        WHERE
            u.status = :status
        ';

        $provider = new SqlDataProvider([
            'sql' => $sql,
            'params' => $params,
            'totalCount' => $count,
            'pagination' => [
                'pageSize' => 10,
            ],
            'sort' => [
                'attributes' => [
                    'username' =>  [
                        'asc' => ['username' => SORT_ASC],
                        'desc' => ['username' => SORT_DESC],
                        'default' => SORT_DESC,
                        'label' => 'e-mail',
                    ],
                    'created_at' =>  [
                        'asc' => ['created_at' => SORT_ASC],
                        'desc' => ['created_at' => SORT_DESC],
                        'default' => SORT_DESC,
                        'label' => 'Дата регистрации',
                    ],
                    'sum_plus' =>  [
                        'asc' => ['sum_plus' => SORT_ASC],
                        'desc' => ['sum_plus' => SORT_DESC],
                        'default' => SORT_DESC,
                        'label' => 'Поступления',
                    ],
                    'sum_minus' =>  [
                        'asc' => ['sum_minus' => SORT_ASC],
                        'desc' => ['sum_minus' => SORT_DESC],
                        'default' => SORT_DESC,
                        'label' => 'Выбытия',
                    ],
                    'balance' =>  [
                        'asc' => ['balance' => SORT_ASC],
                        'desc' => ['balance' => SORT_DESC],
                        'default' => SORT_DESC,
                        'label' => 'Сумма на счете',
                    ],
                ],
            ],
        ]);*/


        $userSearch = new UserSearch();
        $dataProvider = $userSearch->search(Yii::$app->request->get());

        return $this->render('index', [
            //'model' => $this->findModel($id),
            'dataProvider' => $dataProvider,
            'userSearch' => $userSearch,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $params = [':user_id' => $id, ':sender_type' => Transaction::SENDER_TYPE_USER];

        $count = Yii::$app->db->createCommand('
            SELECT COUNT(*) FROM '.Transaction::tableName().' WHERE (sent_by=:user_id AND sender_type=:sender_type) OR received_by=:user_id
        ', $params)->queryScalar();



        $sql = 'SELECT t.id, t.time, t.amount, t.sent_by, t.received_by, t.created_by, t.sender_type, SUM(CASE WHEN t2.received_by = :user_id THEN  t2.amount ELSE 0 END) - SUM(CASE WHEN t2.sent_by = :user_id AND t2.sender_type=:sender_type THEN  t2.amount ELSE 0 END) AS balance_operation
        FROM '.Transaction::tableName().' AS t, '.Transaction::tableName().' AS t2
        WHERE
            ((t.sent_by=:user_id AND t.sender_type=:sender_type) OR t.received_by=:user_id) AND
            ((t2.sent_by=:user_id AND t2.sender_type=:sender_type) OR t2.received_by=:user_id) AND
            t.id >= t2.id
        GROUP BY t.id
        ORDER BY t.id ASC
        ';

        $provider = new SqlDataProvider([
            'sql' => $sql,
            'params' => $params,
            'totalCount' => $count,
            'pagination' => [
                'pageSize' => 10,
            ],
            'sort' => [
                'attributes' => [
                    'time' => SORT_ASC,
                ],
            ],
        ]);

        return $this->render('view', [
            'model' => $this->findModel($id),
            'dataProvider' => $provider,
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new UserAdminForm(['scenario' => 'create']);
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->createUser()) {
                Yii::$app->getSession()->setFlash('success', 'Пользователь успешно добавлен.');
                return $this->redirect(['view', 'id' => $user->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $user = $this->findModel($id);

        $model = new UserAdminForm();

        if ($model->load(Yii::$app->request->post())) {
            if ($model->updateUser($user)) {
                Yii::$app->getSession()->setFlash('success', 'Данные пользователя успешно обновлены.');
                return $this->redirect(['view', 'id' => $user->id]);
            }
        }

        $model->email = $user->username;
        $model->type = $user->type;

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionViewViolator()
    {
        $query = ViolatorLog::find()->joinWith('user')->where([]);//->andFilterWhere(['like', 'user.username', $this->city]);

        $provider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 20,
            ],
            'sort' => [
                'defaultOrder' => [
                    'time' => SORT_DESC,
                ],
                'attributes' => [
                    'username' =>  [
                        'asc' => ['user.username' => SORT_ASC],
                        'desc' => ['user.username' => SORT_DESC],
                        'default' => SORT_DESC,
                        'label' => 'e-mail',
                    ],
                    'time' => [
                        'asc' => ['time' => SORT_ASC],
                        'desc' => ['time' => SORT_DESC],
                        'default' => SORT_DESC,
                        'label' => 'Дата',
                    ],
                    'request' => [
                        'asc' => ['request' => SORT_ASC],
                        'desc' => ['request' => SORT_DESC],
                        'default' => SORT_DESC,
                        'label' => 'Запрос',
                    ],
                ],
            ],
        ]);

        return $this->render('viewViolator', [
            'dataProvider' => $provider,
        ]);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use common\models\User;

/* @var $this yii\web\View */
/* @var $model common\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form" style="width: 300px;">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'type')->dropdownList([User::TYPE_USER => 'Пользователь', User::TYPE_ADMIN => 'Администратор']) ?>

    <div class="form-group">
        <?= Html::submitButton($model->scenario == 'create' ? 'Добавить пользователя' : 'Обновить пользователя', ['class' => $model->scenario == 'create' ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\User;
use yii\helpers\ArrayHelper;

use kartik\date\DatePicker;
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <table class="table-filter">
        <col style="width: 20%;">
        <col style="width: 20%;">
        <col style="width: 20%;">
        <col style="width: 20%;">
        <col style="width: 20%;">
        <tr style="height: 130px;">
            <td>
                <?= $form->field($model, 'username')->dropdownList(ArrayHelper::map(User::findAll(['status' => User::STATUS_ACTIVE]), 'username', 'username'), ['prompt'=>'']) ?>
            </td>

            <td>
                <?= $form->field($model, 'balance') ?>
            </td>

            <td style="text-align: right;">
                <b style="margin-right: 10px;">Дата регистрации:</b>
            </td>

            <td>
                <b>От</b>
                <div style="margin-bottom: 15px;">
                    <?php echo DatePicker::widget([
                        'name'  => 'UserSearch[startRegisterDate]',
                        'value'  => date('d-m-Y', $model->startRegisterDate),
                        'language' => 'ru',
                        'pluginOptions' => [
                            'format' => 'dd-mm-yyyy',
                            'todayHighlight' => true
                        ]
                    ]); ?>
                </div>
            </td>

            <td>
                <b>До</b>
                <div style="margin-bottom: 15px;">
                    <?php echo DatePicker::widget([
                        'name'  => 'UserSearch[endRegisterDate]',
                        'value'  => date('d-m-Y', $model->endRegisterDate),
                        'language' => 'ru',
                        'pluginOptions' => [
                            'format' => 'dd-mm-yyyy',
                            'todayHighlight' => true
                        ]
                    ]); ?>
                </div>
            </td>
        </tr>

        <tr style="height: 130px;">
            <td>
                <?= $form->field($model, 'sum_plus') ?>
            </td>

            <td>
                <?= $form->field($model, 'sum_minus') ?>
            </td>

            <td style="text-align: right;">
                <b style="margin-right: 10px;">Обороты за период:</b>
            </td>

            <td>
                <b>От</b>
                <div style="margin-bottom: 15px;">
                    <?php echo DatePicker::widget([
                        'name'  => 'UserSearch[startPeriodDate]',
                        'value'  => date('d-m-Y', $model->startPeriodDate),
                        'language' => 'ru',
                        'pluginOptions' => [
                            'format' => 'dd-mm-yyyy',
                            'todayHighlight' => true
                        ]
                    ]); ?>
                </div>
            </td>

            <td>
                <b>До</b>
                <div style="margin-bottom: 15px;">
                    <?php echo DatePicker::widget([
                        'name'  => 'UserSearch[endPeriodDate]',
                        'value'  => date('d-m-Y', $model->endPeriodDate),
                        'language' => 'ru',
                        'pluginOptions' => [
                            'format' => 'dd-mm-yyyy',
                            'todayHighlight' => true
                        ]
                    ]); ?>
                </div>
            </td>
        </tr>


    </table>





    <div class="form-group">
        <?= Html::submitButton('Поиск', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Сбросить фильтр', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Добавить пользователя';
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h2><?= Html::encode($this->title) ?></h2>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\models\User;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::$app->name;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <?= $this->render('_search', ['model' => $userSearch]) ?>

    <?php echo GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $userSearch,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'label' => 'Дата регистрации',
                'attribute' => 'created_at',
                'value' => function($data) { return date("Y.m.d H:i:s", $data['created_at']); },
            ],

            [
                'label' => 'Email',
                'attribute' => 'username',
                'value' => function($data) { return Html::a($data['username'], Url::to(['view', 'id' => $data['id']]), []); },
                'format' => 'html',
            ],


            [
                'label' => 'Поступления',
                'attribute' => 'sum_plus',
                'value' => function($data) { return $data['sum_plus'] ? $data['sum_plus'] : '-'; },
            ],

            [
                'label' => 'Выбытия',
                'attribute' => 'sum_minus',
                'value' => function($data) { return $data['sum_minus'] ? $data['sum_minus'] : '-'; },
            ],

            [
                'label' => 'Сумма на счете',
                'attribute' => 'balance',
                'value' => function($data) { return $data['balance']; },
            ],

            [
                'label' => 'Зачислить деньги',
                'value' => function($data) { return Html::a('Зачислить деньги', Url::to(['transaction/enter-sum', 'id' => $data['id']]), ['class' => 'btn btn-success']); },
                'format' => 'html',
            ],

            [
                'label' => 'Отправить деньги',
                'value' => function($data) { return Html::a('Отправить деньги', Url::to(['transaction/create-transfer', 'id' => $data['id']]), ['class' => 'btn btn-warning']); },
                'format' => 'html',
            ],

        ],
    ]);  ?>

</div>

backend/views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Редактирование пользователя';
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-update">

    <h2><?= Html::encode($this->title) ?></h2>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/user/view.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\models\User;
use common\models\Transaction;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Пользователь '.$model->username;
//$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">

    <h2><?= Html::encode($this->title) ?></h2>

    <p>
        <?= Html::a('Редактировать пользователя', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
    </p>

    <?php echo GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'label' => 'Дата операции',
                'attribute' => 'time',
                'value' => function($data) { return date("Y.m.d H:i:s", $data['time']); },
            ],

            [
                'label' => 'Отправитель',
                'attribute' => 'sent_by',
                'value' => function($data) { return User::find()->where(['id' => $data['sent_by']])->one()->username; },
            ],

            [
                'label' => 'Получатель',
                'attribute' => 'received_by',
                'value' => function($data) { return User::find()->where(['id' => $data['received_by']])->one()->username; },
            ],

            [
                'label' => 'Создал операцию',
                'attribute' => 'created_by',
                'value' => function($data) { return User::find()->where(['id' => $data['created_by']])->one()->username; },
            ],

            [
                'label' => 'Сумма',
                'attribute' => 'amount',
                'value' => function($data) { return $data['amount']; },
            ],

            [
                'label' => 'Остаток',
                'attribute' => 'balance_operation',
                'value' => function($data) { return $data['balance_operation']; },
            ],

            [
                'label' => 'Тип операции',
                'attribute' => 'sender_type',
                'value' => function($data) { return Transaction::$nameOperations[$data['sender_type']]; },
            ],

        ],
    ]);  ?>

</div>

backend/views/user/viewViolator.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\models\User;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Нарушители';
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view-violator">

    <h2><?= Html::encode($this->title) ?></h2>


    <?php echo GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'label' => 'Пользователь',
                'attribute' => 'username',
                //'value' => function($data) { return date("Y.m.d H:i:s", $data['time']); },
            ],

            [
                'label' => 'Дата',
                'attribute' => 'time',
                'value' => function($data) { return date("Y.m.d H:i:s", $data->time); },
            ],

            [
                'label' => 'Запрос',
                'attribute' => 'request',
                'value' => function($data) { return $data->request; },
            ],

        ],
    ]);  ?>

</div>