common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\helpers\ArrayHelper;
use common\models\Account;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $email_confirm_token
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
    const TYPE_USER = 0;
    const TYPE_ADMIN = 1;

    const STATUS_BLOCKED = 0;
    const STATUS_ACTIVE = 1;
    const STATUS_WAIT = 2;


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
        /*    ['email', 'required'],
            ['email', 'email'],
            ['email', 'unique', 'targetClass' => self::className(), 'message' => 'This email address has already been taken.'],
            ['email', 'string', 'max' => 255],*/

            ['username', 'required'],
            ['username', 'email'],
            ['username', 'unique', 'targetClass' => self::className(), 'message' => 'Данный емайл уже занят.'],
            ['username', 'string', 'max' => 255],

        /*    ['status', 'integer'],
            ['status', 'default', 'value' => self::STATUS_WAIT],
            ['status', 'in', 'range' => array_keys(self::getStatusesArray())],*/

            ['type', 'integer'],
            ['type', 'default', 'value' => self::TYPE_USER],
            ['type', 'in', 'range' => array_keys(self::getTypeArray())],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Email',
            'status' => 'Статус',
            'type' => 'Тип',
            'created_at' => 'Дата регистрации',
            'password' => 'Пароль',

            'balance' => 'Сумма на счете',
            'sum_plus' => 'Поступления',
            'sum_minus' => 'Выбытия',
        ];
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    /**
     * @param string $email_confirm_token
     * @return static|null
     */
    public static function findByEmailConfirmToken($email_confirm_token)
    {
        return static::findOne(['email_confirm_token' => $email_confirm_token, 'status' => self::STATUS_WAIT]);
    }

    /**
     * Generates email confirmation token
     */
    public function generateEmailConfirmToken()
    {
        $this->email_confirm_token = Yii::$app->security->generateRandomString();
    }

    /**
     * Removes email confirmation token
     */
    public function removeEmailConfirmToken()
    {
        $this->email_confirm_token = null;
    }

    /**
     * название статуса по коду
     */
    public function getStatusName()
    {
        return ArrayHelper::getValue(self::getStatusesArray(), $this->status);
    }

    /**
     * массив статусов
     */
    public static function getStatusesArray()
    {
        return [
            self::STATUS_BLOCKED => 'Заблокирован',
            self::STATUS_ACTIVE => 'Активен',
            self::STATUS_WAIT => 'Ожидает подтверждения',
        ];
    }

    /**
     * название типа пользователя по коду
     */
    public function getTypeName()
    {
        return ArrayHelper::getValue(self::getTypeArray(), $this->type);
    }

    /**
     * массив типов пользователей
     */
    public static function getTypeArray()
    {
        return [
            self::TYPE_USER => 'Пользователь',
            self::TYPE_ADMIN => 'Администратор',
        ];
    }

    /**
     * массив типов пользователей
     */
    public function getCreatedAt()
    {
        return date('Y.m.d', $this->created_at);
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($insert) {
                $this->generateAuthKey();
            }
            return true;
        }
        return false;
    }


    public function getAccount()
    {
        return $this->hasOne(Account::className(), ['user_id' => 'id']);
    }
}

backend/controllers/TransactionController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Transaction;
use common\models\TransactionSearch;
use common\components\CommonController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use backend\models\TransactionAdminForm;
use yii\web\ForbiddenHttpException;
use common\models\ViolatorLog;
use common\models\User;

/**
 * TransactionController implements the CRUD actions for Transaction model.
 */
class TransactionController extends CommonController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }



    /**
     * Creates a new Transaction model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreateTransfer($id)
    {
        $model = new TransactionAdminForm(['scenario' => 'sendMoney']);
        $model->currentUserId = $id;

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->sendMoney();
            Yii::$app->session->setFlash('success', 'Операция успешно проведена.');
            return $this->redirect(['user/view', 'id' => $id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionEnterSum($id)
    {
        $model = new TransactionAdminForm();
        $model->currentUserId = $id;

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->depositMoney();
            Yii::$app->session->setFlash('success', 'Операция успешно проведена.');
            return $this->redirect(['user/view', 'id' => $id]);
        } else {
            return $this->render('enterSum', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Finds the Transaction model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Transaction the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Transaction::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/TransactionController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Transaction;
use common\models\TransactionSearch;
use yii\web\ForbiddenHttpException;
use common\models\User;
use common\components\CommonController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use frontend\models\TransactionUserForm;
use yii\data\SqlDataProvider;
use yii\data\Sort;

/**
 * TransactionController implements the CRUD actions for Transaction model.
 */
class TransactionController extends CommonController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }


    /**
     * Lists all Transaction models.
     * @return mixed
     */
    public function actionIndex()
    {

        $user = User::findOne(Yii::$app->user->id);

        $params = [':user_id' => Yii::$app->user->id, ':sender_type' => Transaction::SENDER_TYPE_USER];

        $count = Yii::$app->db->createCommand('
            SELECT COUNT(*) FROM '.Transaction::tableName().' WHERE (sent_by=:user_id AND sender_type=:sender_type) OR received_by=:user_id
        ', $params)->queryScalar();



        $sql = 'SELECT t.id, t.time, t.amount, t.sent_by, t.received_by, t.created_by, t.sender_type, SUM(CASE WHEN t2.received_by = :user_id THEN  t2.amount ELSE 0 END) - SUM(CASE WHEN t2.sent_by = :user_id AND t2.sender_type=:sender_type THEN  t2.amount ELSE 0 END) AS balance_operation
        FROM '.Transaction::tableName().' AS t, '.Transaction::tableName().' AS t2
        WHERE
            ((t.sent_by=:user_id AND t.sender_type=:sender_type) OR t.received_by=:user_id) AND
            ((t2.sent_by=:user_id AND t2.sender_type=:sender_type) OR t2.received_by=:user_id) AND
            t.id >= t2.id
        GROUP BY t.id
        ORDER BY t.id ASC
        ';


        $provider = new SqlDataProvider([
            'sql' => $sql,
            'params' => $params,
            'totalCount' => $count,
            'pagination' => [
                'pageSize' => 10,
            ],
            'sort' => [
                'attributes' => [
                    'time' => SORT_ASC,
                ],
            ],
        ]);

        return $this->render('index', [
            'dataProvider' => $provider,
            'user' => $user,
        ]);
    }

    /**
     * Displays a single Transaction model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Transaction model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new TransactionUserForm();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if($model->createTransaction()){
                return $this->redirect(['index']);
            }else{
                return $this->redirect(['create', [
                    'model' => $model,
                ]]);
            }
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }


    /**
     * Finds the Transaction model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Transaction the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Transaction::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/transaction/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\User;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\Transaction */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="transaction-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'amount')->textInput() ?>

    <?= $form->field($model, 'received_by')->dropdownList(ArrayHelper::map(User::findAll(['status' => User::STATUS_ACTIVE]), 'id', 'username'), ['prompt'=>'']) ?>


    <div class="form-group">
        <?= Html::submitButton('Перечислить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/transaction/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\TransactionSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="transaction-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'account_id') ?>

    <?= $form->field($model, 'time') ?>

    <?= $form->field($model, 'amount') ?>

    <?= $form->field($model, 'sent_by') ?>

    <?php // echo $form->field($model, 'received_by') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/transaction/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Transaction */

$this->title = 'Новая операция';
$this->params['breadcrumbs'][] = ['label' => 'Операции', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="transaction-create" style="width: 300px;">

    <h2><?= Html::encode($this->title) ?></h2>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>


</div>

frontend/views/transaction/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\models\User;
use common\models\Transaction;

/* @var $this yii\web\View */
/* @var $searchModel app\models\TransactionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Операции';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="transaction-index">

    <h2><?= Html::encode($this->title) ?></h2>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <h3 style="float: right"><?= 'Баланс: '.$user->account->balance.' руб.' ?></h3>

    <p>
        <?= Html::a('Перечислить средства', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?php echo GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'label' => 'Дата операции',
                'attribute' => 'time',
                'value' => function($data) { return date("Y.m.d H:i:s", $data['time']); },
            ],

            [
                'label' => 'Отправитель',
                'attribute' => 'sent_by',
                'value' => function($data) { return User::find()->where(['id' => $data['sent_by']])->one()->username; },
            ],

            [
                'label' => 'Получатель',
                'attribute' => 'received_by',
                'value' => function($data) { return User::find()->where(['id' => $data['received_by']])->one()->username; },
            ],

            [
                'label' => 'Создал операцию',
                'attribute' => 'created_by',
                'value' => function($data) { return User::find()->where(['id' => $data['created_by']])->one()->username; },
            ],

            [
                'label' => 'Сумма',
                'attribute' => 'amount',
                'value' => function($data) { return $data['amount']; },
            ],

            [
                'label' => 'Остаток',
                'attribute' => 'balance_operation',
                'value' => function($data) { return $data['balance_operation']; },
            ],

            [
                'label' => 'Тип операции',
                'attribute' => 'sender_type',
                'value' => function($data) { return Transaction::$nameOperations[$data['sender_type']]; },
            ],

        ],
    ]);  ?>

</div>