frontend/controllers/TransactionController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Transaction;
use common\models\TransactionSearch;
use yii\web\ForbiddenHttpException;
use common\models\User;
use common\components\CommonController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use frontend\models\TransactionUserForm;
use yii\data\SqlDataProvider;
use yii\data\Sort;

/**
 * TransactionController implements the CRUD actions for Transaction model.
 */
class TransactionController extends CommonController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }


    /**
     * Lists all Transaction models.
     * @return mixed
     */
    public function actionIndex()
    {

        $user = User::findOne(Yii::$app->user->id);

        $params = [':user_id' => Yii::$app->user->id, ':sender_type' => Transaction::SENDER_TYPE_USER];

        $count = Yii::$app->db->createCommand('
            SELECT COUNT(*) FROM '.Transaction::tableName().' WHERE (sent_by=:user_id AND sender_type=:sender_type) OR received_by=:user_id
        ', $params)->queryScalar();



        $sql = 'SELECT t.id, t.time, t.amount, t.sent_by, t.received_by, t.created_by, t.sender_type, SUM(CASE WHEN t2.received_by = :user_id THEN  t2.amount ELSE 0 END) - SUM(CASE WHEN t2.sent_by = :user_id AND t2.sender_type=:sender_type THEN  t2.amount ELSE 0 END) AS balance_operation
        FROM '.Transaction::tableName().' AS t, '.Transaction::tableName().' AS t2
        WHERE
            ((t.sent_by=:user_id AND t.sender_type=:sender_type) OR t.received_by=:user_id) AND
            ((t2.sent_by=:user_id AND t2.sender_type=:sender_type) OR t2.received_by=:user_id) AND
            t.id >= t2.id
        GROUP BY t.id
        ORDER BY t.id ASC
        ';


        $provider = new SqlDataProvider([
            'sql' => $sql,
            'params' => $params,
            'totalCount' => $count,
            'pagination' => [
                'pageSize' => 10,
            ],
            'sort' => [
                'attributes' => [
                    'time' => SORT_ASC,
                ],
            ],
        ]);

        return $this->render('index', [
            'dataProvider' => $provider,
            'user' => $user,
        ]);
    }

    /**
     * Displays a single Transaction model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Transaction model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new TransactionUserForm();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if($model->createTransaction()){
                return $this->redirect(['index']);
            }else{
                return $this->redirect(['create', [
                    'model' => $model,
                ]]);
            }
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }


    /**
     * Finds the Transaction model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Transaction the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Transaction::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Операции', 'url' => ['/transaction/index']],
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Зарегистрироваться', 'url' => ['/site/signup']];
        $menuItems[] = ['label' => 'Войти', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Выйти (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>